language: go

go:
    - 1.6
    - tip

notifications:
    email: 
        recipients:
            - davorkapsa@gmail.com
        on_success: never
        on_failure: always

script:
    - ./travis.sh

after_success:
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov fails"
