language: go

sudo: false

go:
    - 1.6
    - tip

notifications:
    email: 
        recipients:
            - davorkapsa@gmail.com
        on_success: never
        on_failure: always

before_install:
    - go get github.com/mattn/goveralls

script:
    - $HOME/gopath/bin/goveralls 

