language: go

go:
    - 1.4
    - tip

notifications:
    email: false

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

