language: go

go:
  - master

env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org

git:
  depth: 1

install: true

branches:
  only:
  - master



script:
  - go test -v -race -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
