language: go

go:
    - 1.5
    - tip

notifications:
    email: 
        recipients:
            - davorkapsa@gmail.com
        on_success: never
        on_failure: always

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls

script:
    - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

