language: go

go:
    - 1.8
    - tip

notifications:
    email: 
        recipients:
            - davor.kapsa@gmail.com
        on_success: never
        on_failure: always

script:
    - make test

after_success:
    - make codecov
