name: Test
on:
  push:
  schedule:
    - cron:  '0 0 * * *' 
jobs:
  test:
    name: Ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
      id: go
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -v -race -cover ./...
