name: Test and coverage
on:
  push:
  schedule:
    - cron:  '0 0 * * *' 
jobs:
  test:
    name: Ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.x
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version: 1.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run vet, tests and coverage
      run: go test -race -cover -shuffle=on -vet=all ./...

