name: Test and coverage
on:
  push:
  schedule:
    - cron:  '0 0 * * *' 
jobs:
  test:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests and coverage
      run: go test -race -cover -shuffle=on ./...

