name: Test and coverage
on:
  push:
  schedule:
    - cron:  '0 0 * * *' 
jobs:
  test:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run vet, tests and coverage
      run: go test -race -cover -shuffle=on -vet=all ./...

